# theme.toml template for a Hugo theme
# See https://github.com/gohugoiox/hugoThemes#themetoml for an example
# NOTE: Update these values when forking this theme for your project

name = "PROJECT_NAME"
license = "MIT"
licenselink = "https://QuanMofii.github.io/site-documentation/blob/main/LICENSE"
description = "Modern, responsive, batteries-included Hugo theme for creating beautiful static websites."
homepage = "https://QuanMofii.github.io/site-documentation"
demosite = "https://QuanMofii.github.io/site-documentation"
tags = ["Modern", "Elegant", "Blog", "Documentation", "Responsive", "Clean", "Light", "Dark", "Minimal"]
features = ["Responsive", "Dark Mode", "Search", "Syntax Highlighting", "Multilingual", "Social", "Blog", "RSS", "Customization"]
min_version = "0.146.0"

[author]
  name = "QuanMofii"
  homepage = "https://QuanMofii.github.io"
