# theme.toml template for a Hugo theme
# See https://github.com/gohugoiox/hugoThemes#themetoml for an example
# NOTE: Update these values when forking this theme for your project

name = "PROJECT_NAME"
license = "MIT"
licenselink = "https://github.com/{author}/{project_name}/blob/main/LICENSE"
description = "Modern, responsive, batteries-included Hugo theme for creating beautiful static websites."
homepage = "https://github.com/{author}/{project_name}/"
demosite = "https://{author}.github.io/{project_name}/"
tags = ["Modern", "Elegant", "Blog", "Documentation", "Responsive", "Clean", "Light", "Dark", "Minimal"]
features = ["Responsive", "Dark Mode", "Search", "Syntax Highlighting", "Multilingual", "Social", "Blog", "RSS", "Customization"]
min_version = "0.146.0"

[author]
  name = "{author}"
  homepage = "https://{author}.github.io"
